trigger: none

jobs:
  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
    parameters:
      Artifacts:
        - name: azure-data-tables
          groupId: com.azure
          safeName: azuretables
      CloudConfig:
        SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
        Cloud: Public
      MatrixConfigs:
        MatrixConfigs:
          - Name: Tables_live_test
            Path: sdk/tables/platform-matrix.json
            Selection: sparse
            GenerateVMJobs: true
      AdditionalParameters:
        ServiceDirectory: tables
        Timeout: 60
        MaxParallel: 14
        EnvVars:
          AZURE_TEST_MODE: LIVE
